export const API_BASE_URL: string = 'http://localhost:3000/api/v2';
export const OAUTH2_REDIRECT_URI: string = 'http://localhost:5173/oauth2/redirect';

export const GOOGLE_AUTH_URL: string = API_BASE_URL + '/oauth2/authorize/google?redirect_uri=' + OAUTH2_REDIRECT_URI;
export const GITHUB_AUTH_URL: string = API_BASE_URL + '/oauth2/authorize/github?redirect_uri=' + OAUTH2_REDIRECT_URI;



export const languages = [
    'Javascript',
    'Typescript',
    'Python',
    'Java',
    'C++',
    'C#',
    'Ruby',
    'PHP',
    'Swift',
    'Kotlin',
    'Rust',
    'Go',
    'Scala',
    'Perl',
    'Lua',
    'Haskell',
    'Erlang',
    'Clojure',
    'F#',
    'R',
    'Dart',
    'Julia',
    'Groovy',
    'Objective-C',
    'Shell',
    'PowerShell',
    'SQL',
    'HTML',
    'CSS',
    'SASS',
    'LESS',
    'SCSS',
    'Stylus',
    'PostCSS',
    'GraphQL'
]

export const technologies = [
    'TailwindCSS',
    'Bootstrap',
    'Materialize',
    'Bulma',
    'Ant Design',
    'Chakra UI',
    'Material UI',
    'Semantic UI',
    'Foundation',
    'UIKit',
    'Flutter',
    'React',
    'Vue',
    'Angular',
    'Svelte',
    'Ember',
    'Backbone',
    'Meteor',
    'Polymer',
    'Aurelia',
    'Mithril',
    'Preact',
    'Alpine.js',
    'Stimulus',
    'Marko',
    'Solid.js',
    'Blitz.js',
    'Nuxt.js',
    'Next.js',
    'Gatsby',
    'Sapper',
    'Gridsome',
    'Astro',
    'Redwood.js',
    'AngularJS',
    'jQuery',
    'Lodash',
    'Underscore',
    'Moment.js',
    'Day.js',
    'Luxon',
    'date-fns',
    'Ramda',
    'RxJS',
    'Redux',
    'MobX',
    'Vuex',
    'Apollo',
    'Relay',
    'React Query',
    'SWR',
    'Zustand',
    'Recoil',
    'Jotai',
    'Redux Toolkit',
    'Easy Peasy',
    'Overmind',
    'MobX State Tree',
    'XState',
    'React Hook Form',
    'Formik',
    'Yup',
    'Zod',
    'Joi',
    'Superstruct',
    'Ajv',
    'Yup',
    'Zod',
    'Joi',
    'Superstruct',
    'Ajv',
    'React Router',
    'Reach Router',
    'Next.js Router',
    'Vue Router',
    'Nuxt.js Router'
]

export const categories = [
    'Computer Science',
    'Software Engineering',
    'Web Development',
    'Mobile Development',
    'Game Development',
    'Data Science',
    'Machine Learning',
    'Artificial Intelligence',
    'Cybersecurity',
    'Cloud Computing',
    'DevOps',
    'Blockchain',
    'Internet of Things',
    'Big Data',
    'Quantum Computing',
    'Augmented Reality',
    'Virtual Reality',
    'Embedded Systems',
    'Robotics',
    'Natural Language Processing',
    'Computer Vision',
    'Human-Computer Interaction',
    'User Experience Design',
    'User Interface Design',
    'Frontend Development',
    'Backend Development',
    'Fullstack Development',
    'Database Management',
    'Network Engineering',
    'Systems Administration',
    'IT Support',
    'Technical Writing',
    'Technical Training',
    'Project Management',
    'Product Management',
    'Quality Assurance',
    'Software Testing',
    'Software Architecture',
    'Software Development',
    'Software Maintenance',
    'Software Deployment',
    'Software Documentation',
    'Software Licensing',
    'Software Compliance',
    'Software Security',
    'Software Auditing',
    'Software Monitoring',
    'Software Optimization',
    'Software Debugging',
    'Software Performance',
    'Software Scalability',
    'Software Reliability',
    'Software Resilience',
    'Software Recovery',
    'Software Backup',
    'Software Restoration',
    'Software Migration',
    'Software Integration',
    'Software Interoperability',
    'Software Portability',
    'Software Usability',
    'Software Accessibility',
    'Software Inclusivity',
    'Software Diversity',
    'Software Equity',
    'Software Ethics',
    'Software Governance',
    'Software Regulation',
    'Software Compliance',
    'Software Auditing',
    'Software Monitoring',
    'Software Optimization',
    'Software Debugging',
    'Software Performance',
    'Software Scalability',
    'Software Reliability',
    'Software Resilience',
    'Software Recovery',
    'Software Backup',
    'Software Restoration',
    'Software Migration',
    'Software Integration',
    'Software Interoperability',
    'Software Portability',
    'Software Usability',
    'Software Accessibility',
    'Software Inclusivity',
    'Software Diversity',
    'Software Equity',
    'Software Ethics',
    'Software Governance',
    'Software Regulation',
    'Software Compliance',
    'Software Auditing',
    'Software Monitoring',
    'Software Optimization',
    'Software Debugging',
    'Software Performance',
    'Software Scalability',
    'Software Reliability',
    'Software Resilience',
    'Software Recovery',
    'Software Backup',
    'Software Restoration',
    'Software Migration',
    'Software Integration',
    'Software Interoperability',
    'Software Portability',
    'Software Usability',
    'Software Accessibility',
    'Software Inclusivity',
    'Software Diversity',
    'Software Equity',
    'Software Ethics'
]



// export const WORKFLOW_TOKEN = "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"
export const WORKFLOW_TOKEN = "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"
export const JSON_BIN_SECRET_KEY = "$2a$10$dphGuG0AlshHCKlTODtqK.POOl2Igv6i0RB8wT2C9wv2/F60vwbhu"
export const JSON_BIN_ID = "669ed082e41b4d34e415aae3"

